# Generated by Django 3.0.11 on 2021-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('my_rating', models.FloatField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('original_publication_year', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
