# Generated by Django 3.2.8 on 2021-10-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('goodreads', '0001_initial'), ('goodreads', '0002_exportdata_user'), ('goodreads', '0003_authors'), ('goodreads', '0004_auto_20210922_0305_squashed_0010_exportdata_ts_updated'), ('goodreads', '0005_auto_20211016_2009')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('author_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality1', models.CharField(blank=True, max_length=80, null=True)),
                ('nationality2', models.CharField(blank=True, max_length=80, null=True)),
                ('nationality_chosen', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('shelf1', models.CharField(max_length=250, null=True)),
                ('shelf2', models.CharField(max_length=250, null=True)),
                ('shelf3', models.CharField(max_length=250, null=True)),
                ('shelf4', models.CharField(max_length=250, null=True)),
                ('shelf5', models.CharField(max_length=250, null=True)),
                ('shelf6', models.CharField(max_length=250, null=True)),
                ('shelf7', models.CharField(max_length=250, null=True)),
                ('added_by', models.IntegerField(blank=True, default=0, null=True)),
                ('to_reads', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExportData',
            fields=[
                ('book_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('my_rating', models.FloatField(blank=True, null=True)),
                ('average_rating', models.FloatField(blank=True, null=True)),
                ('original_publication_year', models.FloatField(blank=True, null=True)),
                ('shelf1', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf2', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf3', models.CharField(blank=True, max_length=250, null=True)),
                ('username', models.CharField(default='Random', max_length=30)),
                ('added_by', models.IntegerField(blank=True, default=0, null=True)),
                ('narrative', models.CharField(default='Fiction', max_length=250, null=True)),
                ('to_reads', models.IntegerField(blank=True, default=0, null=True)),
                ('shelf4', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf5', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf6', models.CharField(blank=True, max_length=250, null=True)),
                ('shelf7', models.CharField(blank=True, max_length=250, null=True)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
