# Generated by Django 3.2.6 on 2023-01-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodreads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportdata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
