# Generated by Django 3.2.6 on 2021-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdata',
            name='user',
            field=models.CharField(default='Random', max_length=30, unique=True),
        ),
    ]
