# Generated by Django 3.2.6 on 2021-09-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0002_exportdata_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=250)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality1', models.CharField(blank=True, max_length=80, null=True)),
                ('nationality2', models.CharField(blank=True, max_length=80, null=True)),
                ('nationality_chosen', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
    ]
