# Generated by Django 3.2.8 on 2021-10-17 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0002_auto_20211017_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportdata',
            options={'managed': True},
        ),
    ]
