# Generated by Django 3.2.6 on 2023-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodreads", "0003_spotify"),
    ]

    operations = [
        migrations.AddField(
            model_name="spotifytracks",
            name="genre_chosen",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
