# Generated by Django 3.2.6 on 2022-04-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0003_alter_exportdata_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdata',
            name='exclusive_shelf',
            field=models.CharField(default='read', max_length=30),
        ),
    ]
