# Generated by Django 3.2.6 on 2021-09-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    #replaces = [('goodreads', '0004_auto_20210922_0305'), ('goodreads', '0005_auto_20210923_0319'), ('goodreads', '0006_auto_20210923_0326'), ('goodreads', '0007_auto_20210928_0443'), ('goodreads', '0008_auto_20210928_1820'), ('goodreads', '0009_auto_20210930_0327'), ('goodreads', '0010_exportdata_ts_updated')]

    dependencies = [
        ('goodreads', '0003_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdata',
            name='added_by',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='narrative',
            field=models.CharField(default='Fiction', max_length=250, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportdata',
            name='to_reads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='authors',
            name='id',
        ),
        migrations.AlterField(
            model_name='authors',
            name='author_name',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('book_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('shelf1', models.CharField(max_length=250)),
                ('shelf2', models.CharField(max_length=250)),
                ('shelf3', models.CharField(max_length=250)),
                ('shelf4', models.CharField(max_length=250)),
                ('shelf5', models.CharField(max_length=250)),
                ('shelf6', models.CharField(max_length=250)),
                ('shelf7', models.CharField(max_length=250)),
                ('added_by', models.IntegerField(blank=True, default=0, null=True)),
                ('to_reads', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='shelf4',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='shelf5',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='shelf6',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='shelf7',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='date_read',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='exportdata',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='username',
            field=models.CharField(default='Random', max_length=30),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='ts_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
