# Generated by Django 3.2.8 on 2021-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0004_auto_20210922_0305_squashed_0010_exportdata_ts_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportdata',
            name='id',
            field=models.IntegerField(default=1234, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf2',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf3',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf4',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf5',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf6',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='shelf7',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='book_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf3',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf4',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf5',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf6',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='exportdata',
            name='shelf7',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
