# Generated by Django 3.2.6 on 2022-05-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0004_auto_20220403_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefNationality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=250, null=True)),
                ('nationality', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
