# Generated by Django 3.2.6 on 2022-07-14 05:13

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0005_auto_20220507_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportdata',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='narrative',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf1',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf2',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf3',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf4',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf5',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf6',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='shelf7',
        ),
        migrations.RemoveField(
            model_name='exportdata',
            name='to_reads',
        ),
        migrations.AddField(
            model_name='books',
            name='narrative',
            field=models.CharField(default='Fiction', max_length=250),
        ),
        migrations.AddField(
            model_name='exportdata',
            name='id',
            field=models.AutoField(auto_created=True, default=builtins.id, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
