# Generated by Django 3.2.6 on 2022-08-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0006_auto_20220714_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetflixTitles',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('cast', models.CharField(max_length=500)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(max_length=250, null=True)),
                ('duration', models.CharField(max_length=250, null=True)),
                ('country1', models.CharField(max_length=250, null=True)),
                ('country2', models.CharField(max_length=250, null=True)),
                ('country3', models.CharField(max_length=250, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('listed_in', models.CharField(max_length=250)),
                ('ts_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetflixUsers',
            fields=[
                ('title', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True)),
                ('username', models.CharField(max_length=30)),
            ],
        ),
    ]
