# Generated by Django 3.2.6 on 2023-06-15 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goodreads", "0008_auto_20230608_0245"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyArtist",
            fields=[
                (
                    "uri",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("artist_name", models.CharField(max_length=250, null=True)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("followers_total", models.IntegerField(blank=True, null=True)),
                ("genres", models.CharField(max_length=1000, null=True)),
                ("image_url", models.CharField(max_length=1000, null=True)),
                ("ts_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="spotifytracks",
            name="artist_uri",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
