# Generated by Django 3.2.6 on 2023-07-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0009_spotifyartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='netflixtitles',
            name='alt_votes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='netflixtitles',
            name='default_image',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
