# Generated by Django 3.2.6 on 2023-07-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0010_auto_20230722_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netflixtitles',
            name='default_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
