# Generated by Django 3.2.6 on 2024-07-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0011_alter_netflixtitles_default_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('list_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='netflixactors',
            name='cast',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='netflixgenres',
            name='genres',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='netflixtitles',
            name='director',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='netflixtitles',
            name='title_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyartist',
            name='artist_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='spotifyartist',
            name='genres',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spotifyartist',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='bookslists',
            constraint=models.UniqueConstraint(fields=('title', 'list_name'), name='unique_book_list'),
        ),
    ]
