# Generated by Django 5.0.7 on 2024-09-05 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goodreads", "0013_auto_20240724_1904"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLists",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="bookslists",
            name="unique_book_list",
        ),
        migrations.AddConstraint(
            model_name="bookslists",
            constraint=models.UniqueConstraint(
                fields=("title", "list_name", "book_id"), name="unique_book_list"
            ),
        ),
        migrations.AddField(
            model_name="userlists",
            name="list_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goodreads.bookslists",
            ),
        ),
        migrations.AddField(
            model_name="userlists",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
