# Generated by Django 5.0.7 on 2024-08-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goodreads", "0013_auto_20240724_1904"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookslists",
            name="unique_book_list",
        ),
        migrations.AddConstraint(
            model_name="bookslists",
            constraint=models.UniqueConstraint(
                fields=("title", "list_name", "book_id"), name="unique_book_list"
            ),
        ),
    ]
