from django.db import models


class ExportData(models.Model):
    book_id = models.CharField(max_length=250)
    title = models.CharField(max_length=250)
    author = models.CharField(max_length=250)
    # author_l_f = models.CharField(max_length=250)
    # additional_authors = models.CharField(max_length=250)
    # isbn = models.CharField(max_length=250)
    # isbn13 = models.CharField(max_length=250)
    # my_rating = models.CharField(max_length=250)
    # average_rating = models.CharField(max_length=250)
    # publisher = models.CharField(max_length=250)
    # binding = models.CharField(max_length=250)
    # number_of_pages = models.CharField(max_length=250)
    # year_published = models.CharField(max_length=250)
    # original_pub_year = models.CharField(max_length=250)
    # date_read = models.CharField(max_length=250)
    # date_added = models.CharField(max_length=250)
    # bookshelves = models.CharField(max_length=250)
    # bookshelves_with_positions = models.CharField(max_length=250)
    # exclusive_shelf = models.CharField(max_length=250)
    # my_review = models.TextField()
    # spoiler = models.CharField(max_length=2500)
    # private_notes = models.CharField(max_length=2500)
    # read_count = models.CharField(max_length=250)
    # recommended_for = models.CharField(max_length=250)
    # recommended_by = models.CharField(max_length=250)
    # owned_copies = models.CharField(max_length=250)
    # original_purchase_date = models.CharField(max_length=250)
    # original_purchase_location = models.CharField(max_length=250)
    # condition = models.CharField(max_length=250)
    # condition_description = models.CharField(max_length=250)
    # bcid = models.CharField(max_length=250)
