from django.urls import path
from django.views.generic import RedirectView
from django.conf.urls import url
from .views import *

urlpatterns = [
    path("", index, name="index-view"),
    path("books/upload-csv/", upload_view_goodreads, name="upload-view-goodreads"),
    path("upload-goodreads/", upload_goodreads, name="upload-goodreads"),
    path("insert-goodreads/", insert_goodreads, name="insert-goodreads"),
    path("upload-spotify-home", upload_view_spotify, name="upload-spotify"),
    path("music/upload-json-spotify/", upload_spotify, name="json-upload-spotify"),
    path("insert-spotify/", insert_spotify, name="insert-spotify"),
    path("run-script/", runscript, name="run-script"),
    path("run-script-spotify/", runscriptSpotify, name="run-script-spotify"),
    path("run-script-netflix/", runscriptNetflix, name="run-script-netflix"),
    path("nationality-map/", nationality_map_view, name="nationality-map"),
    path("popularity-spectrum/", popularity_spectrum_view, name="popularity-spectrum"),
    path("about-this/", about_this, name="about-this"),
    path("about-this-spotify/", about_this_spotify, name="about-this-spotify"),
    path("about-this-netflix/", about_this_netflix, name="about-this-netflix"),
    path("books/home/", books_home, name="books-home"),
    path("music/home/", music_home, name="music-home"),
    path("books/plots/", plots_view, name="plots"),
    path("geography/", geography, name="geography-home"),
    path("streaming/", streaming, name="streaming-home"),
    path("faq/", faq, name="faq"),
    url(r"^favicon\.ico$", RedirectView.as_view(url="/static/admin/img/favicon.ico")),
    path("spotify-plots/", spot_plots_view, name="spotify-plots"),
    path("upload-view-netflix/", upload_view_netflix, name="upload-view-netflix"),
    path("upload-netflix/", upload_netflix, name="upload-netflix"),
    path("insert-netflix/", insert_netflix, name="insert-netflix"),
    path("netflix-plots/", netflix_plots_view, name="netflix-plots"),
    path("books/gallery/", gallery_books, name="gallery-books"),
    path("music/gallery", gallery_music, name="gallery-music"),
    path("streaming/gallery", gallery_streaming, name="gallery-streaming"),
    path("gallery-geography/", gallery_geography, name="gallery-geography"),
    path("spot-text/", spot_text, name="spot-text"),
    path("comments/", comments, name="comments"),
    path("post-comment/", post_comment, name="post-comment"),
    path("streaming/compare/", netflix_compare_view, name="netflix-compare-view"),
    path("streaming/compare-func/", netflix_compare_func, name="netflix-compare-func"),
    path("good-text/", good_text, name="good-text"),
    path("books/view-data", view_data_books, name="books-view-data"),
    path("music/view-data", view_data_music, name="music-view-data"),
]
